settings:
  # INSTANT - начисление сразу после убийства моба.
  # COLLECTING - начисление после подбора уникального предмета, выпавшего с моба.
  type-drop: INSTANT
  boosters: # ВНИМАНИЕ! Вводить именно ID группы. Только в формате плавающей точки.
    default: 1.0
    vip: 1.5
    premium: 2.0

  percent: 10 # процент выпадаемых монет с игрока.

item-settings: # Настройки предмета.
  item-id: EXPERIENCE_BOTTLE
  enchant-effect: true

messages:
  help: "&#37FF00&l[WakeMobs] &a/wakemobs reload &7- &fперезагрузить конфигурацию."
  reload: "&#37FF00&l[WakeMobs] &fКонфигруация &aуспешно&f перезагружена."
  no-money: "&fВы &#FF0000не получили&f монет с моба." # Сообщение, только в actionbar. (Для того, чтобы не засорять чат.)

# Слушатели
# Выполняют ряд команд относительно ивенту.
# ENTITY_DEATH - смерть сущности (моба)
#   Команды:
#   [message] - отправить сообщение игроку убийце
#   [title] - отправить титульное сообщение игроку убийце
#   [actionbar] - отправить актионбар сообщение.
#   [sound] - проиграть музыку
#   Плейсхолдеры:
#   {mob-name} - имя моба из mobs-settings.yml
#   {money} - монеты полученные с моба
#   {booster} - бустер игрока.
# PLAYER_DEATH_ENVIRONMENT - смерть игрока от окружающей среды
#   Команды:
#   [message] - отправить сообщение умершему игроку.
#   [title] - отправить титульное сообщение умершему игроку.
#   [actionbar] - отправить актионбар сообщение умершему игроку.
#   [sound] - проиграть музыку
#   Плейсхолдеры:
#   {world} - мир смерти
#   {money} - потерянные монеты
#   {x} - координата X смерти
#   {y} - координата Y смерти
#   {z} - координата Z смерти
# KILLING_PLAYER - смерть игрока от рук другого игрока.
#   Команды:
#   [message] - отправить сообщение умершему игроку.
#   [title] - отправить титульное сообщение умершему игроку.
#   [actionbar] - отправить актионбар сообщение умершему игроку.
#   [sound] - проиграть музыку
#   Плейсхолдеры:
#   {world} - мир смерти
#   {money} - потерянные монеты
#   {killer} - ник убийцы
#   {x} - координата X смерти
#   {y} - координата Y смерти
#   {z} - координата Z смерти
# MONEY_FROM_PLAYER - получение монет при убийстве игрока.
#   Команды:
#   [message] - отправить сообщение убийце
#   [title] - отправить титульное сообщение убийце
#   [actionbar] - отправить актионбар сообщение убийце
#   [sound] - проиграть музыку
#   Плейсхолдеры:
#   {money} - полученные монеты.
#   {player} - ник умершего
# PICKUP_ITEM_FROM_ENTITY - подбор монетного предмета с моба
#   Команды:
#   [message] - отправить сообщение убийце
#   [title] - отправить титульное сообщение убийце
#   [actionbar] - отправить актионбар сообщение убийце
#   [sound] - проиграть музыку
#   Плейсхолдеры:
#   {money} - полученные монеты.
#   {mob-name} - имя моба из mobs-settings.yml
#   {booster} - бустер игрока
# PICKUP_ITEM_FROM_PLAYER - подбор монетного предмета с игрока
#   Команды:
#   [message] - отправить сообщение убийце
#   [title] - отправить титульное сообщение убийце
#   [actionbar] - отправить актионбар сообщение убийце
#   [sound] - проиграть музыку
#   Плейсхолдеры:
#   {money} - полученные монеты.
#   {player} - ник умершего

listeners:
  ENTITY_DEATH:
    commands:
      - "[sound] ENTITY_PLAYER_LEVELUP;1;1"
      - "[actionbar] &#37FF00[ℹ] &fВы получили &e{money}$ &fза убийство {mob-name}&f. &7[&ax{booster}&7]"
  PLAYER_DEATH_ENVIRONMENT:
    commands:
      - "[message] &c[☠] &fПомянем. Вы погибли!"
      - "[message] &f    &fКоординаты: &a[{x}, {y}, {z}]"
      - "[message] &f    &fИз-за смерти вы потеряли: &e{money}$ &fмонет."
  KILLING_PLAYER:
    commands:
      - "[message] &c[☠] &fПомянем. Вы погибли!"
      - "[message] &f    &fКоординаты: &a[{x}, {y}, {z}]"
      - "[message] &f    &fВас убил &6{killer}&f, вы потеряли &e{money}$"
  MONEY_FROM_PLAYER:
    commands:
      - "[message] &fВы получили &e{money}$ &fиз-за смерти игрока &a{player}"
  PICKUP_ITEM_FROM_ENTITY:
    commands:
      - "[sound] ENTITY_PLAYER_LEVELUP;1;1"
      - "[actionbar] &#37FF00[ℹ] &fВы подобрали &e{money}$ &fс {mob-name}&f. &7[&ax{booster}&7]"
  PICKUP_ITEM_FROM_PLAYER:
    commands:
      - "[message] &fВы подобрали &e{money}$ &fс игрока &a{player}"